[package]
name = "load-img-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lodepng = "3.5.2"
glob = "0.3.0"
rgb = "0.8.31"