[package]
name = "load-img-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lodepng = "3.6.0"
glob = "0.3.0"
rgb = "0.8.31"
nalgebra = "0.30.1"
ndarray-npy = "0.8.1"
ndarray = "0.15.4"