
GET http://127.0.0.1:5000/?name=test
###
POST http://127.0.0.1:5000/echo
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}
###
GET http://127.0.0.1:5000/get-pointcloud?project=corner01
###
GET http://127.0.0.1:5000/get-mesh?project=corner01
###
GET http://127.0.0.1:5000/get-project-names
###
GET http://127.0.0.1:5000/get-camera-poses?project=corner01
###
GET http://127.0.0.1:5000/get-laser-poses?project=corner01
###
GET http://127.0.0.1:5000/get-cam-laser-poses?project=corner01