[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.3"
lodepng = "3.6.1"
kd-tree = "0.4.1"
bvh = "0.6.0"
